# Generated by Django 3.2 on 2022-09-26 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zmyapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=32)),
                ('cursos_asignados', models.IntegerField()),
            ],
        ),
    ]
