# Generated by Django 3.2 on 2022-09-26 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zmyapp', '0002_instructor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='nombre',
            field=models.CharField(max_length=128, unique=b'I01\n'),
        ),
    ]
